<a href="https://colab.research.google.com/github/Jcrt/dcc127-data-mining/blob/main/Trabalho_4_%5BJulio_e_Daniel%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
from google.colab import drive
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [59]:
drive.mount('/content/drive')
dados = pd.read_csv("/content/drive/MyDrive/trabalho4_dados_07.csv")

dados

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

      ABSORVENTE  ACETONA  ACHOCOLATADO  ...  VELA  VERDURAS  VINAGRE
0     0           0        0             ...  0     0         0
1     0           0        0             ...  0     0         0
2     0           0        0             ...  0     0         0
3     0           0        0             ...  0     0         0
4     0           0        0             ...  0     0         0
...  ..          ..       ..             ... ..    ..        ..
5638  0           0        0             ...  0     0         0
5639  0           0        0             ...  0     0         0
5640  0           0        0             ...  0     0         0
5641  0           0        0             ...  0     0         0
5642  0           0        0             ...  0     0         0

[5643 rows x 137 columns]

# Suporte mínimo
****
Para calcular o suporte mínimo, iniciamos os testes com 0.1, e isso significa que os produtos devem estar presentes em 10% da base de dados, o que nos retornou quatro produtos isolados.

In [67]:
itemsets = apriori(dados, min_support=0.1, use_colnames=True)

itemsets

    support        itemsets
0  0.214957  (BISCOITO)
1  0.156831  (OLEO_VEGETAL)
2  0.104554  (PAES)
3  0.150097  (QUEIJOS)

# Ajuste de suporte mínimo
****
Fomos reduzindo o suporte mínimo até chegarmos em um número que julgamos interessante. Com o suporte mínimo em 0.007, a regra de suporte mínimo exigiria que os ítens estivessem na mesma compra por, pelo menos, 40 vezes para serem uma possível combinação frequente.

In [87]:
itemsets = apriori(dados, min_support=0.017, use_colnames=True)

itemsets

      support                       itemsets
0    0.017189  (ABSORVENTE)
1    0.043062  (ACHOCOLATADO)
2    0.049973  (ACUCAR)
3    0.020556  (AGUA)
4    0.036860  (ARROZ)
..        ...      ...
98   0.018784  (BISCOITO, CREME, CAFE)
99   0.017367  (BISCOITO, CHOCOLATE, FRUTAS)
100  0.022683  (CREME, OLEO_VEGETAL, CAFE)
101  0.018430  (PALMITO, CREME, CAFE)
102  0.017189  (CREME, PROD_LIMPEZA, CAFE)

[103 rows x 2 columns]

# Verificação de suporte
****
Efetuamos alguns testes com as combinações geradas no *step* anterior e, para as instâncias geradas, todas geraram um número igual ou maior a 95

In [93]:
d1 = dados[(dados["CREME"] == 1) & (dados["PROD_LIMPEZA"] == 1) & (dados["CAFE"] == 1)]
print("Total de linhas:", len(d1.index))

Total de linhas: 97

#Descobrindo regras de associação
****
Para descobrir as regras de associação, iniciamos o limiar de confiança mínima em 0.5 e foram retornadas muitas regras de associação.

In [95]:
regras = association_rules(itemsets, metric="confidence", min_threshold=0.5)

print("Total de regras de associação:", len(regras.index))
regras.sort_values(by="lift",  ascending=False)

Total de regras de associação: 28

              antecedents         consequents  ...  leverage  conviction
7   (FAROFA)               (CEREAL)            ...  0.018261  inf
8   (CEREAL)               (FAROFA)            ...  0.018261  inf
14  (GELEIA)               (COMIDA_PET)        ...  0.019283  inf
13  (COMIDA_PET)           (GELEIA)            ...  0.019283  inf
5   (ESPELHO)              (CARNE_SUINA)       ...  0.019454  inf
6   (CARNE_SUINA)          (ESPELHO)           ...  0.019454  inf
2   (CREME_DE_LEITE)       (BOLOS)             ...  0.020813  inf
1   (BOLOS)                (CREME_DE_LEITE)    ...  0.020813  inf
11  (COMIDA_CONGELADA)     (GELATINA)          ...  0.028218  inf
12  (GELATINA)             (COMIDA_CONGELADA)  ...  0.028218  inf
9   (CHOCOLATE)            (FRUTAS)            ...  0.051128  inf
10  (FRUTAS)               (CHOCOLATE)         ...  0.051128  inf
20  (BISCOITO, CHOCOLATE)  (FRUTAS)            ...  0.016428  inf
21  (BISCOITO, FRUTAS)     (CHOCOLATE)         ...  0.016428  inf
25  (PALMITO, CAFE)        (CREME)             ...  0.017202  inf
26  (CREME, PROD_LIMPEZA)  (CAFE)              ...  0.016044  inf
24  (PALMITO, CREME)       (CAFE)              ...  0.017202  inf
23  (OLEO_VEGETAL, CAFE)   (CREME)             ...  0.021172  inf
22  (CREME, OLEO_VEGETAL)  (CAFE)              ...  0.021172  inf
27  (PROD_LIMPEZA, CAFE)   (CREME)             ...  0.016044  inf
19  (BISCOITO, CAFE)       (CREME)             ...  0.017533  inf
18  (BISCOITO, CREME)      (CAFE)              ...  0.017533  inf
17  (ACUCAR, CAFE)         (CREME)             ...  0.020510  inf
16  (ACUCAR, CREME)        (CAFE)              ...  0.020510  inf
4   (CAFE)                 (CREME)             ...  0.062192  inf
3   (CREME)                (CAFE)              ...  0.062192  inf
15  (GORDURA_VEGETAL)      (PAES)              ...  0.026659  inf
0   (ACHOCOLATADO)         (BISCOITO)          ...  0.012718  1.603072

[28 rows x 9 columns]

#Ajustando as regras de associação
****
Como foram geradas muitas regras de associação, aumentamos o limiar mínimo para 0.99, o que nos gerou cerca de 270 ítens com regras de associação. 
Isso nos revela que todas as regras de associação descobertas são fortes.

In [91]:
regras = association_rules(itemsets, metric="confidence", min_threshold=0.99)

print("Total de regras de associação:", len(regras.index))
regras.sort_values(by="lift",  ascending=False)

Total de regras de associação: 27

              antecedents         consequents  ...  leverage  conviction
7   (CEREAL)               (FAROFA)            ...  0.018261  inf
6   (FAROFA)               (CEREAL)            ...  0.018261  inf
13  (GELEIA)               (COMIDA_PET)        ...  0.019283  inf
12  (COMIDA_PET)           (GELEIA)            ...  0.019283  inf
4   (ESPELHO)              (CARNE_SUINA)       ...  0.019454  inf
5   (CARNE_SUINA)          (ESPELHO)           ...  0.019454  inf
1   (CREME_DE_LEITE)       (BOLOS)             ...  0.020813  inf
0   (BOLOS)                (CREME_DE_LEITE)    ...  0.020813  inf
10  (COMIDA_CONGELADA)     (GELATINA)          ...  0.028218  inf
11  (GELATINA)             (COMIDA_CONGELADA)  ...  0.028218  inf
8   (CHOCOLATE)            (FRUTAS)            ...  0.051128  inf
19  (BISCOITO, CHOCOLATE)  (FRUTAS)            ...  0.016428  inf
9   (FRUTAS)               (CHOCOLATE)         ...  0.051128  inf
20  (BISCOITO, FRUTAS)     (CHOCOLATE)         ...  0.016428  inf
25  (CREME, PROD_LIMPEZA)  (CAFE)              ...  0.016044  inf
24  (PALMITO, CAFE)        (CREME)             ...  0.017202  inf
23  (PALMITO, CREME)       (CAFE)              ...  0.017202  inf
22  (OLEO_VEGETAL, CAFE)   (CREME)             ...  0.021172  inf
21  (CREME, OLEO_VEGETAL)  (CAFE)              ...  0.021172  inf
17  (BISCOITO, CREME)      (CAFE)              ...  0.017533  inf
18  (BISCOITO, CAFE)       (CREME)             ...  0.017533  inf
16  (ACUCAR, CAFE)         (CREME)             ...  0.020510  inf
15  (ACUCAR, CREME)        (CAFE)              ...  0.020510  inf
2   (CREME)                (CAFE)              ...  0.062192  inf
3   (CAFE)                 (CREME)             ...  0.062192  inf
26  (PROD_LIMPEZA, CAFE)   (CREME)             ...  0.016044  inf
14  (GORDURA_VEGETAL)      (PAES)              ...  0.026659  inf

[27 rows x 9 columns]